[[inputs]]
name = "polybench-partial"
paths = ["benchmarks/polybench-partial/*.fuse"]
stage_dynamic_config = [
    ["synth-verilog.tcl", "synth.tcl"],
    ["synth-verilog.constraints", "device10.xdc"],
    ["calyx.flags", ""],
]

[[inputs]]
name = "calyx examples"
paths = ["benchmarks/calyx-examples/*.futil"]
config.source = "calyx"
stage_dynamic_config = [
    ["synth-verilog.tcl", "synth.tcl"],
    ["synth-verilog.constraints", "device10.xdc"],
    ["calyx.flags", ""],
]
