[[inputs]]
name = "polybench-partial"
paths = [
  "benchmarks/polybench-partial/*.fuse"
]
config.stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['futil.flags', '']]

[[inputs]]
name = "calyx examples"
paths = [
  "benchmarks/calyx-examples/*.futil"
]
config.stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['futil.flags', '']]

