[[inputs]]
name = "polybench"
paths = [
  "benchmarks/polybench/*.fuse"
]
stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['calyx.flags', '']]

[[inputs]]
name = "big"
paths = [
  "benchmarks/big/*.futil"
]
config.source = "calyx"
stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['calyx.flags', '']]

[[inputs]]
name = "tcam"
paths = [
  "benchmarks/tcam/*.futil"
]
config.source = "calyx"
stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['calyx.flags', '']]


[[inputs]]
name = "ntt"
paths = [
  "benchmarks/ntt/*.futil"
]
config.source = "calyx"
stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['calyx.flags', '']]


[[inputs]]
name = "calyx examples"
paths = [
  "benchmarks/calyx-examples/*.futil"
]
config.source = "calyx"
stage_dynamic_config = [['synth-verilog.tcl', 'synth.tcl'], ['synth-verilog.constraints', 'device10.xdc'], ['calyx.flags', '']]

